# Generated by Django 4.2.5 on 2023-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='messages',
            field=models.TextField(blank=True, default=''),
        ),
    ]
