# Generated by Django 4.2.5 on 2023-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_customuser_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='tovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('data_add', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images_tovar/')),
            ],
        ),
    ]
